a lot of ObjectTypeFilter was created on the widget activate, not all of them are removed.
Error: create part, extrusion, sketch - > it is not possible to select a sketch plane.